name: Upload mcpack

on:
 push:
   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v4
    - name: Remove Useless folder
      run: |
        rm -rf ./.git
        rm -rf ./.github
        rm ./README.md

    - name: Pack Minecraft-Bedrock-Edition-ms_CN.zip
      run: zip -r Minecraft-Bedrock-Edition-ms_CN.zip ./

    - name: Rename Minecraft-Bedrock-Edition-ms_CN.mcpack
      run: mv Minecraft-Bedrock-Edition-ms_CN.zip Minecraft-Bedrock-Edition-ms_CN.mcpack
      
    - name: Upload mcpack
      uses: actions/upload-artifact@v4
      with:
        name: Minecraft-Bedrock-Edition-ms_CN
        path: Minecraft-Bedrock-Edition-ms_CN.*
