name: Upload mcpack

on:
 push:
   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v4
    - name: Create .mcpack file
      uses: mzyxsl/minecraft-pack-action@v1.0.0
      with:
        output-filename: 'Minecraft-Bedrock-Edition-ms_CN'
      
    - name: Upload mcpack
      uses: actions/upload-artifact@v4
      with:
        name: Minecraft-Bedrock-Edition-ms_CN
        path: Minecraft-Bedrock-Edition-ms_CN.*
