name: Upload mcpack

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Remove .git folder
      run: rm -rf ./.git

    - name: Remove .github folder
      run: rm -rf ./.github

    - name: Remove README.md
      run: README.md

    - name: Pack Minecraft-Bedrock-Edition-ms_CN.zip
      run: zip -r Minecraft-Bedrock-Edition-ms_CN.zip ./

    - name: Rename Minecraft-Bedrock-Edition-ms_CN.mcpack
      run: mv Minecraft-Bedrock-Edition-ms_CN.zip Minecraft-Bedrock-Edition-ms_CN.mcpack
      
    - name: Upload mcpack
      uses: actions/upload-artifact@v4
      with:
        name: Minecraft-Bedrock-Edition-ms_CN
        path: Minecraft-Bedrock-Edition-ms_CN.*
