name: PullLint
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
jobs:
  # This workflow closes invalid PR
  close-pr:
    name: closepr
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Close PR if commit message contains ".json"
        if: contains(github.event.pull_request.title, '.json')
        uses: superbrothers/close-pull-request@v3
        with:
          # Optional. Post a issue comment just before closing a pull request.
          comment: "非法PR. 请勿修改主仓库的配置文件"
